{
  "number": 7862,
  "title": "MSBuild task returned false but did not log an error",
  "body": "@jordi1215 showed me that the GenerateDepsFile task failed. It had presumably been invoked via an MSBuild task invocation, as it also logged two \"MSBuild task returned false but did not log an error\" errors. Before logging that error, we should ensure that no task invoked as a result of executing the current task logged an error.",
  "state": "CLOSED",
  "createdAt": "2022-08-04T22:57:44Z",
  "updatedAt": "2022-08-05T16:55:04Z",
  "closedAt": "2022-08-05T16:55:04Z",
  "author": {
    "login": "Forgind"
  },
  "labels": [
    "bug",
    "needs-triage"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "> task invoked as a result of executing the current task\r\n\r\nCan you elaborate on this please?",
        "createdAt": "2022-08-05T14:31:02Z",
        "updatedAt": "2022-08-05T14:31:02Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "I didn't spend any time investigating, but at a glance, it looked like:\r\nMSBuild task invoked, specifying some target -->\r\ntarget includes GenerateDepsFile task, which fails and logs an error, then returns false -->\r\nMSBuild task returns false but doesn't log an error.\r\n\r\nI seem to remember we had some logic to prevent this from happening, but I'm wondering if that's broken in some way. I should've asked for logs; will do that later today if he still has it up.",
        "createdAt": "2022-08-05T15:26:39Z",
        "updatedAt": "2022-08-05T15:26:39Z",
        "author": {
          "login": "Forgind"
        }
      },
      {
        "body": "Sadly, he didn't. This probably isn't actually actionable.",
        "createdAt": "2022-08-05T16:55:04Z",
        "updatedAt": "2022-08-05T16:55:04Z",
        "author": {
          "login": "Forgind"
        }
      }
    ]
  }
}