{
  "number": 5150,
  "title": "Unlogged error in RAR (?)",
  "body": "@sharwell reported offline an IDE build that suddenly failed without any error messages. He was able to capture an exception using PerfView\r\n\r\n```\r\nSystem.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.\r\n   at System.Reflection.AssemblyName.nGetFileInformation(String s)\r\n   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)\r\n   at Microsoft.Build.Shared.AssemblyNameExtension.GetAssemblyNameEx(String path)\r\n   at Microsoft.Build.Tasks.SystemState.GetAssemblyName(String path)\r\n   at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryAssemblyReferenceItem(ITaskItem referenceAssemblyName)\r\n   at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryItems(ITaskItem[] referenceAssemblyFiles, ITaskItem[] referenceAssemblyNames, List`1 exceptions)\r\n   at Microsoft.Build.Tasks.ReferenceTable.ComputeClosure(IEnumerable`1 remappedAssembliesValue, ITaskItem[] referenceAssemblyFiles, ITaskItem[] referenceAssemblyNames, List`1 exceptions)\r\n   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetRegistrySubKeyNames getRegistrySubKeyNames, GetRegistrySubKeyDefaultValue getRegistrySubKeyDefaultValue, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, OpenBaseKey openBaseKey, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)\r\n   at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()\r\n   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<InitializeAndExecuteTask>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteBucket>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__51.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__21.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__58.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__50.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__49.MoveNext()\r\n```",
  "state": "OPEN",
  "createdAt": "2020-02-28T16:08:23Z",
  "updatedAt": "2024-02-21T16:29:49Z",
  "closedAt": null,
  "author": {
    "login": "rainersigwald"
  },
  "labels": [
    "Area: Debuggability",
    "Area: Task: Resolve Assembly References (RAR)",
    "triaged"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": {
    "title": "Backlog"
  },
  "comments": {
    "nodes": [
      {
        "body": "@Forgind can you try injecting an exception at that callsite and seeing if we really do swallow it without logging a useful error?",
        "createdAt": "2020-02-28T16:08:54Z",
        "updatedAt": "2020-02-28T16:08:54Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "I inserted the OutOfMemoryException in AssemblyNameExtension.cs, and when I forced it to execute it, I got this:\r\n```C:\\Users\\forgind\\Documents\\GitHub\\msbuild>artifacts\\bin\\bootstrap\\net472\\MSBuild\\Current\\Bin\\MSBuild.exe MSBuild.Dev.sln /m:1\r\nMicrosoft (R) Build Engine version 16.6.0-dev-20128-01+13cfe7fc5 for .NET Framework\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\n  Microsoft.Build.Framework -> C:\\Users\\forgind\\Documents\\GitHub\\msbuild\\artifacts\\bin\\Microsoft.Build.Framework\\Debug\r\n  \\netstandard2.0\\Microsoft.Build.Framework.dll\r\n  Microsoft.Build -> C:\\Users\\forgind\\Documents\\GitHub\\msbuild\\artifacts\\bin\\Microsoft.Build\\Debug\\netcoreapp2.1\\Micro\r\n  soft.Build.dll\r\n  Microsoft.Build.Framework -> C:\\Users\\forgind\\Documents\\GitHub\\msbuild\\artifacts\\bin\\Microsoft.Build.Framework\\Debug\r\n  \\net472\\Microsoft.Build.Framework.dll\r\n  Xunit.NetCore.Extensions -> C:\\Users\\forgind\\Documents\\GitHub\\msbuild\\artifacts\\bin\\Xunit.NetCore.Extensions\\Debug\\n\r\n  etstandard2.0\\Xunit.NetCore.Extensions.dll\r\n  PortableTask -> C:\\Users\\forgind\\Documents\\GitHub\\msbuild\\artifacts\\bin\\Samples\\PortableTask\\Debug\\netstandard1.3\\Po\r\n  rtableTask.dll\r\n\r\nBuild FAILED.\r\n    0 Warning(s)\r\n    0 Error(s)\r\n\r\nTime Elapsed 00:02:29.32\r\n```\r\n\r\nLooks like a real problem to me.\r\n\r\n(Build from command line.)",
        "createdAt": "2020-02-28T17:28:21Z",
        "updatedAt": "2020-02-28T17:28:59Z",
        "author": {
          "login": "Forgind"
        }
      },
      {
        "body": "I did, however, get this to pop up:\r\n![image](https://user-images.githubusercontent.com/12969783/75571515-372d9e80-5a0e-11ea-9efb-f43d80cab4d8.png)\r\nIt's possible that only came up because I was building from the command line. Either way, there's a problem here. Also, it disappeared as soon as the build finished. Perhaps worse than failing with no warnings or errors, it also noted in a diagnostic build log that the RAR task had failed but gave no reason why.",
        "createdAt": "2020-02-28T17:49:32Z",
        "updatedAt": "2020-02-28T18:17:32Z",
        "author": {
          "login": "Forgind"
        }
      },
      {
        "body": "@Forgind I think those dialogs pop up for debug builds but not release--might be worth trying with the `Release` config to see if it goes away.\r\n\r\nSounds like the next steps here are to catch the initial exception in a debugger and step forward to see what's catching it.",
        "createdAt": "2020-02-28T18:57:29Z",
        "updatedAt": "2020-02-28T18:57:29Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "This seems to only happen when an exception is classified as a critical exception, as OutOfMemoryExceptions are. Such exceptions are swallowed twice: once [here](https://github.com/microsoft/msbuild/blob/master/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L701) (note that [`ErrorUtilities.ThrowInternalError`](https://github.com/microsoft/msbuild/blob/master/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L710) prevents execution, so the throw isn't hit) and once [here](https://github.com/microsoft/msbuild/blob/master/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L621).\r\n\r\nI'm going to unassign myself for now until this starts becoming a major issue.",
        "createdAt": "2020-03-03T18:53:59Z",
        "updatedAt": "2020-03-03T18:53:59Z",
        "author": {
          "login": "Forgind"
        }
      },
      {
        "body": "@Forgind I hit this ~~5~~ ~~6~~ ~~7~~ ~~8~~ ~~9~~ ~~10~~ ~~11~~ ~~12~~ ~~13~~ ~~14~~ ~~15~~ ~~16~~ ~~17~~ ~~18~~ ~~19~~ ~~20~~ ~~21~~ ~~22~~ ~~23~~ ~~24~~ ~~25~~ ~~26~~ ~~27~~ ~~28~~ ~~29~~ ~~30~~ ~~31~~ ~~32~~ ~~33~~ ~~34~~ ~~35~~ ~~36~~ ~~37~~ 45 more times this morning (using 16.7 Preview 1)",
        "createdAt": "2020-05-20T14:55:16Z",
        "updatedAt": "2020-05-20T22:43:49Z",
        "author": {
          "login": "sharwell"
        }
      },
      {
        "body": "@Forgind Apparently this is just my life now \ud83d\ude22 ",
        "createdAt": "2020-05-20T20:44:51Z",
        "updatedAt": "2020-05-20T20:44:51Z",
        "author": {
          "login": "sharwell"
        }
      },
      {
        "body": "@Forgind I hit this 2 times so far today.",
        "createdAt": "2020-05-21T18:01:38Z",
        "updatedAt": "2020-05-21T18:01:38Z",
        "author": {
          "login": "sharwell"
        }
      },
      {
        "body": "What if we just remove this block? Wouldn't the `finally` section ensure the exception gets logged?\r\n\r\nhttps://github.com/microsoft/msbuild/blob/ba9a1d64a7abf15a8505827c00413156a3eb7f62/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L754-L761",
        "createdAt": "2020-05-22T17:05:19Z",
        "updatedAt": "2020-05-22T17:05:19Z",
        "author": {
          "login": "sharwell"
        }
      },
      {
        "body": "> What if we just remove this block? Wouldn't the `finally` section ensure the exception gets logged?\r\n> \r\n> https://github.com/microsoft/msbuild/blob/ba9a1d64a7abf15a8505827c00413156a3eb7f62/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L754-L761\r\n\r\nThe finally section runs either way, and without this block, a critical exception can't percolate to the top layer and display the full stack. The OOM exception is caught either way, as it is now, but that would additionally block other exceptions.",
        "createdAt": "2020-05-22T18:10:45Z",
        "updatedAt": "2020-05-22T18:10:45Z",
        "author": {
          "login": "Forgind"
        }
      },
      {
        "body": "I'm hitting this again this morning \u2639\ufe0f ",
        "createdAt": "2020-06-09T13:44:23Z",
        "updatedAt": "2020-06-09T13:44:23Z",
        "author": {
          "login": "sharwell"
        }
      }
    ]
  }
}