{
  "number": 3217,
  "title": "VS2017 15.6.6 ON PUBLISH TO AZURE: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Task Instance should be null",
  "body": "### Publishing .net core mvc to azure fails after build\r\n\r\nWhen initiating publish to Azure from within Visual Studio 2017 15.6.6 it builds correctly. \r\nJust in the moment when it starts the publishing process it fails with a rather not helpful error message:\r\n\r\n> One or more errors occured\r\n\r\nThe Application compiles and runs perfectly fine locally and even if y publish it by hand to Azure it works with no issues.\r\n\r\n**VS Output Window:**\r\n========== Build: 1 succeeded, 0 failed, 7 up-to-date, 0 skipped ==========\r\n========== Publish: 0 succeeded, 1 failed, 0 skipped ==========\r\n\r\nthe VS error list is empty.  The VS Error Message points to a temp file.\r\n\r\n## Log File in Temp directory:\r\n\r\n`\"23.04.2018 08:09:25\r\nSystem.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Exception: Fehler beim Ver\u00f6ffentlichen aufgrund von Buildfehlern. \u00dcberpr\u00fcfen Sie die Fehlerliste auf weitere Details.\r\n   --- Ende der internen Ausnahmestapel\u00fcberwachung ---\r\n   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   bei Microsoft.VisualStudio.Web.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass40_0.<PublishAsync>b__2()\r\n   bei System.Threading.Tasks.Task`1.InnerInvoke()\r\n   bei System.Threading.Tasks.Task.Execute()\r\n--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__88.MoveNext()\r\n===================\"\r\n\r\n## MSBuild_de291e9e-0db7-4f0e-9622-1185230b6c28.failure in my Temp Directory:\r\n\"23.04.2018 08:09:25\r\nMicrosoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Task Instance should be null\r\n   bei Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)\r\n   bei Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.CleanupForTask()\r\n   bei Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__18.MoveNext()\r\n--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__13.MoveNext()\r\n--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__52.MoveNext()\r\n--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   bei Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__45.MoveNext()\r\n--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   bei Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__21.MoveNext()\r\n--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   bei Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()\r\n--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   bei Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57.MoveNext()\r\n--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49.MoveNext()\r\n--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48.MoveNext()\r\n===================\"`\r\n\r\nProject file\r\n```xml\r\n<Project Sdk=\"Microsoft.NET.Sdk.Web\">\r\n\r\n  <PropertyGroup>\r\n    <TargetFramework>netcoreapp2.0</TargetFramework>\r\n  </PropertyGroup>\r\n\r\n  <ItemGroup>\r\n    <PackageReference Include=\"IdentityServer4\" Version=\"2.2.0\" />\r\n    <PackageReference Include=\"IdentityServer4.AspNetIdentity\" Version=\"2.1.0\" />\r\n    <PackageReference Include=\"IdentityServer4.EntityFramework\" Version=\"2.1.1\" />\r\n    <PackageReference Include=\"Microsoft.AspNetCore.All\" Version=\"2.0.7\" />\r\n  </ItemGroup>\r\n\r\n  <ItemGroup>\r\n    <ProjectReference Include=\"..\\Tricon360.Web.TagHelpers\\Tricon360.Web.TagHelpers.csproj\" />\r\n  </ItemGroup>\r\n\r\n</Project>\r\n```\r\n\r\n### Expected  behavior\r\nIt should publish my app to Azure\r\n\r\n### Actual behavior\r\nIt fails\r\n\r\n### Environment data\r\n`msbuild /version` output:\r\n\r\nOS info: Windows 10 Pro 1709 16299.371\r\n\r\nIf applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):\r\nVisual Studio 2017 15.6.6\r\n.net core SDK 2.1.105",
  "state": "CLOSED",
  "createdAt": "2018-04-23T06:55:50Z",
  "updatedAt": "2024-02-21T17:13:29Z",
  "closedAt": "2018-07-11T03:04:33Z",
  "author": {
    "login": "ctonger"
  },
  "labels": [
    "triaged"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "Hi all, \r\n\r\nMay I say that this is a very frustrating issue for me, as this used to work for me on and off with previous VS2017 Versions.  (There were always periods of problems up from Visual Studio 2017)\r\n\r\n**I should add that I can perfectly publish to a local folder and from there via FTP to Azure.** \r\n\r\nIt is only when publishing to Azure that I get this exception. For both my asp.net core projects in my solution. \r\n\r\nFTP however is not a good option as I have to halt the app service in order to not miss files due to file lock issues. Also the fact that the servers are not 100% in sync time wise I always have to do a full ftp publish which depending on the Network I am on may take up to 2 hours.\r\n\r\n### Another thing I noticed: \r\nIf I Create a new ASP.NET Core Project and publish it as is without touching it, it works. So it doesn't seem to be that there is a general issue. \r\n\r\n### What I have done so far:\r\n1. I have recreated the project I reported from scratch. Which was quite some work but I wanted to see if it could be solved like this. It can't.\r\n\r\n2. I have double and Triple checked all Views in order to see if it could be a compilation issue, which I noticed if in release build also won't through meaningful exceptions. So I always do a debug publish beforehand to catch those if there are any. The views compile fine.\r\n\r\n3. I have double checked that all packages are up to date.\r\n\r\n4. I have removed all Typescript dependencies as this has caused similar issues on previous occasions (also not recently) and I am not using Typescript at present (although I would like to). \r\n\r\n5. I have deactivated all WebCompliling of JS and LESS prior to build in order to avoid possible interference with the build process. I never the less also double checked that there are no missing files in the web compiler config file.\r\n\r\n6. I have completely removed all references to ApplicationInsights and TelemetryClient and have deactivated the service on Azure and also removed the resource group, just to make sure that the issue is not there.\r\n\r\n7. I have disconnected all references between Azure and VS Online. I also hace removed previous continuous delivery options from Visual Studios, including the corresponding Azure slots in order to be as simple as possible. I also have recreated the App Services (which in self was a pain for having to re-associate all domains etc...)\r\n\r\n8. Endless times I have re-created the publish profiles not using any fancy option.\r\n\r\n## I NEED HELP!!!!\r\n\r\n",
        "createdAt": "2018-04-24T06:36:15Z",
        "updatedAt": "2018-04-24T06:42:41Z",
        "author": {
          "login": "ctonger"
        }
      },
      {
        "body": "I have the same issue.  Did you find a solution?",
        "createdAt": "2018-07-29T15:03:48Z",
        "updatedAt": "2018-07-29T15:03:48Z",
        "author": {
          "login": "Dell-Simmons"
        }
      },
      {
        "body": "Not that only one that I could point to. \r\n\r\nWhat worked was publishing local and then via FTP. \r\n\r\nThen, just before completely going nuts I deleted my Azure App Service and made a factory re-set on my mashine. But that did not kill the issue either.\r\n\r\nI then decided to try a new local publish and  FTP publishing to azure.  And after this I gave it another try to publish to azure directly and all of a suddon it works. \r\n\r\nI was a week or so stuck on this.\r\n\r\nIt was the third time that I was facing an issue like this. This was so annoying not to get a decent exception and no help at all.... It always happened after a VS Upgrade....",
        "createdAt": "2018-08-05T00:04:57Z",
        "updatedAt": "2018-08-05T00:04:57Z",
        "author": {
          "login": "ctonger"
        }
      }
    ]
  }
}