{
  "number": 604,
  "title": "ResolveComReference should fail the build and not rethrow exceptions; Task Execution should consider remote exceptions from tasks",
  "body": "During a multiprocess build, the ResolveComReference is called in another appdomain and crashes. This causes the TaskExecutionHost to throw a remoting exception, as shown from a crash dump:\n\n```\n1.system_threading!System.Threading.Thread.InternalCrossContextCallback\n2.system_runtime!System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessage\n3.system_runtime!System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage\n4.system_runtime!System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch\n5.system_runtime!System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback\n6.system_threading!System.Threading.Thread.CompleteCrossContextCallback\n7.mscorlib!System.Threading.Thread.InternalCrossContextCallback\n8.mscorlib!System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatch\n9.mscorlib!System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage\n10.mscorlib!System.Runtime.Remoting.Proxies.RemotingProxy.CallProcessMessage\n11.mscorlib!System.Runtime.Remoting.Proxies.RemotingProxy.InternalInvoke\n12.mscorlib!System.Runtime.Remoting.Proxies.RemotingProxy.Invoke\n13.mscorlib!System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke\n14.microsoft_build_framework!Microsoft.Build.Framework.ITask.Execute\n15.microsoft_build!Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute\n```\n\nThere are two action items: \n1. Change [ResolveComReference](https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/ResolveComReference.cs#L397) to fail the build instead of re-throwing exception\n2. Change either [TaskExecutionHost](https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeBuildEngine/BackEnd/TaskExecutionHost/TaskExecutionHost.cs#L632) or someone higher in the call stack to treat the case where a remote task crashes and propagates back a remote exception.\n\nTracked internally: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=187118\n",
  "state": "OPEN",
  "createdAt": "2016-05-04T00:04:11Z",
  "updatedAt": "2024-02-21T16:38:40Z",
  "closedAt": null,
  "author": {
    "login": "cdmihai"
  },
  "labels": [
    "help wanted",
    "triaged"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": null,
  "comments": {
    "nodes": []
  }
}