{
  "number": 3656,
  "title": "Exception stack trace and MSB4018 when cancelling the build",
  "body": "_From @Tragetaschen on August 27, 2018 11:7_\n\nI just cancelled a build (CTRL+C) and got a big wall of red text on the console:\r\n```\r\nEs wird versucht, den Buildvorgang abzubrechen...\r\nPS [\u2026]> C:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018: Unerwarteter Fehler bei der Csc-Aufgabe. [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Safe handle has been closed)) ---> System.AggregateException: One or more errors occurred. (Safe handle has been closed) ---> System.ObjectDisposedException: Safe handle has been closed [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at Interop.Kernel32.CancelIoEx(SafeHandle handle, NativeOverlapped* lpOverlapped) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.IO.Pipes.PipeCompletionSource`1.Cancel() [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018: --- End of stack trace from previous location where exception was thrown --- [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    --- End of inner exception stack trace --- [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    --- End of inner exception stack trace --- [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Cancel() [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018: ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Safe handle has been closed) ---> System.ObjectDisposedException: Safe handle has been closed [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at Interop.Kernel32.CancelIoEx(SafeHandle handle, NativeOverlapped* lpOverlapped) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.IO.Pipes.PipeCompletionSource`1.Cancel() [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018: --- End of stack trace from previous location where exception was thrown --- [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    --- End of inner exception stack trace --- [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018: ---> (Inner Exception #0) System.ObjectDisposedException: Safe handle has been closed [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at Interop.Kernel32.CancelIoEx(SafeHandle handle, NativeOverlapped* lpOverlapped) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.IO.Pipes.PipeCompletionSource`1.Cancel() [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018: --- End of stack trace from previous location where exception was thrown --- [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)<--- [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018: <--- [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): error MSB4018:  [[\u2026].csproj]\r\nC:\\Program Files\\dotnet\\sdk\\2.1.400\\Roslyn\\Microsoft.CSharp.Core.targets(52,5): warning MSB5021: Die ausf\u00fchrbare Datei der Aufgabe \"dotnet\" und zugeh\u00f6rige Prozesse werden beendet, weil die Builderstellung abgebrochen wurde. [[\u2026].csproj]\r\n```\n\n_Copied from original issue: dotnet/sdk#2497_",
  "state": "CLOSED",
  "createdAt": "2018-08-27T14:47:48Z",
  "updatedAt": "2024-02-21T17:11:39Z",
  "closedAt": "2021-09-11T19:01:09Z",
  "author": {
    "login": "rainersigwald"
  },
  "labels": [
    "bug",
    "needs-more-info",
    "stale",
    "closed-by-bot",
    "triaged"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "@Tragetaschen is this happening often for you? I can't quite tell from the stack trace exactly what's going wrong, unfortunately. It's not clear to me what MSBuild code is running to throw this error.",
        "createdAt": "2018-08-27T14:49:24Z",
        "updatedAt": "2018-08-27T14:49:24Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "Unfortunately(?) no. This is the first time and I have cancelled a fair number of dotnet publish commands during the build step on the command line.",
        "createdAt": "2018-08-27T14:51:38Z",
        "updatedAt": "2018-08-27T14:51:38Z",
        "author": {
          "login": "Tragetaschen"
        }
      },
      {
        "body": "Ok, thanks. If you (or anyone!) start to detect any sort of pattern that leads to this please let us know.",
        "createdAt": "2018-08-27T15:01:06Z",
        "updatedAt": "2018-08-27T15:01:06Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "I just got it a second time. This was with SDK version `2.2.101` and shows exactly the same stack trace as above when cancelling.",
        "createdAt": "2018-12-17T08:54:23Z",
        "updatedAt": "2018-12-17T08:54:23Z",
        "author": {
          "login": "Tragetaschen"
        }
      },
      {
        "body": "This issue is marked as stale because feedback has been requested for 30 days with no response. Please respond within 14 days or this issue will be closed due to inactivity.",
        "createdAt": "2021-08-28T00:01:24Z",
        "updatedAt": "2021-08-28T00:01:24Z",
        "author": {
          "login": "ghost"
        }
      },
      {
        "body": "This issue was closed due to inactivity. If you can still reproduce this bug, please comment with the requested information, detailed steps to reproduce the problem, or any other notes that might help in the investigation.",
        "createdAt": "2021-09-11T19:01:10Z",
        "updatedAt": "2021-09-11T19:01:10Z",
        "author": {
          "login": "ghost"
        }
      }
    ]
  }
}