{
  "number": 9025,
  "title": "[Unhandled Exception]: System.OutOfMemoryException: Insufficient memory to continue the execution of the program - Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()",
  "body": "### Issue Description\r\n\r\nWe are trying to build a big solution (1K+ projects), and we are receiving the following exception - these are different builds, but it seems that the code is broken on the same place:\r\n\r\n```\r\nSystem.OutOfMemoryException: Insufficient memory to continue the execution of the program.\r\n   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()\r\n   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n\r\nSystem.AggregateException: One or more errors occurred. ---> Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Insufficient memory to continue the execution of the program.\r\n\r\nSystem.OutOfMemoryException: Insufficient memory to continue the execution of the program.\r\n   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()\r\n   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n```\r\n\r\n### Steps to Reproduce\r\n\r\nWe are running the MSBuild from Azure DevOps Self-Hosted Agent on AKS Cluster using mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 base image. Using .Net Framework 4.6 on a x64 architecture.\r\n\r\nThe Node has 22GB and 6CPU core.\r\n\r\nThese are the MSBuild parameters: `msbuildArguments: '/p:RestoreLockedMode=true /p:GenerateBuildInfoConfigFile=false /p:RegisterForComInterop=\"false\" /p:BuildInParallel=\"true\" /nr:false /property:CopyRetryCount=20;CopyRetryDelayMilliseconds=2000 /verbosity:normal /nodeReuse:false'`\r\n\r\n### Actual Behavior\r\n\r\n**Example1:**\r\n\r\n```\r\nSystem.OutOfMemoryException: Insufficient memory to continue the execution of the program.\r\n   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()\r\n   at Microsoft.Build.BackEnd.RequestBuilder.SaveOperatingEnvironment()\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<StartNewBuildRequests>d__61.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProjects>d__40.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskHost.<BuildProjectFilesInParallelAsync>d__84.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskHost.<InternalBuildProjects>d__80.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Build.BackEnd.MSBuild.<ExecuteTargets>d__80.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.MSBuild.<BuildProjectsInParallel>d__77.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.MSBuild.<ExecuteInternal>d__76.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<InitializeAndExecuteTask>d__24.MoveNext()\r\n End of stack trace from previous location where exception was thrown \r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteBucket>d__19.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__18.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__13.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__51.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__68.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n```\r\n\r\n\r\n\r\n\r\n**Example2:**\r\n\r\n```\r\nSystem.AggregateException: One or more errors occurred. ---> Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: One or more errors occurred.\r\n\r\nSystem.OutOfMemoryException: Insufficient memory to continue the execution of the program.\r\n   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()\r\n   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()\r\nEnd of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n\r\nSystem.OutOfMemoryException: Insufficient memory to continue the execution of the program.\r\n   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()\r\n   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()\r\n End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.WaitForCancelCompletion()\r\n   at Microsoft.Build.BackEnd.BuildRequestEngine.<CleanupForBuild>b__41_0()\r\n   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass72_0.<QueueAction>b__0()\r\n---> (Inner Exception #0) Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Insufficient memory to continue the execution of the program.\r\n\r\nSystem.OutOfMemoryException: Insufficient memory to continue the execution of the program.\r\n   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()\r\n   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n\r\n ---> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.\r\n   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()\r\n   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.WaitForCancelCompletion()\r\n   at Microsoft.Build.BackEnd.BuildRequestEngine.<CleanupForBuild>b__41_0()\r\n   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass72_0.<QueueAction>b__0()\r\n```\r\n\r\n\r\n\r\n### Analysis\r\n\r\nIt seems that this is a parallelism issue, when we move the parameter maxcpucount to 1, then the issue is not occurring.\r\n\r\n### Versions & Configurations\r\n\r\nMSBuild version 17.6.3+07e294721 for .NET Framework\r\n17.6.3.22601",
  "state": "CLOSED",
  "createdAt": "2023-07-13T07:03:38Z",
  "updatedAt": "2024-02-21T14:04:16Z",
  "closedAt": "2023-09-24T19:01:05Z",
  "author": {
    "login": "rmoreirao"
  },
  "labels": [
    "bug",
    "needs-more-info",
    "stale",
    "closed-by-bot",
    "triaged"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "Interesting. There apparently historicaly was an allocations optimisation of involved code for win arch already: https://github.com/dotnet/msbuild/issues/2402\r\n\r\nWould you be able to collect a dump of the crash, and if possible ETW trace of the build as well (`perfview collect /NoGui /Providers=*Microsoft-Build /BufferSize:8096 /CircularMB:8096 /NoNGenRundown /DataFile:oom-repro`) and share with us? (uploading to any internal share would do)",
        "createdAt": "2023-07-13T12:28:42Z",
        "updatedAt": "2023-07-13T12:28:42Z",
        "author": {
          "login": "JanKrivanek"
        }
      },
      {
        "body": "Hi @JanKrivanek , thanks for the reply. To run this, can I just run the command after the MSBuild command? This is running into an Azure DevOps Agent - so not so easy to access the machine.\r\n",
        "createdAt": "2023-07-13T13:12:55Z",
        "updatedAt": "2023-07-13T13:12:55Z",
        "author": {
          "login": "rmoreirao"
        }
      },
      {
        "body": "ETW needs to be collect from separate process, that will be started before the build and ctrl-c closed after the build. For ADO run, this might be more complicated. Can you consult your engineering services / infrastructure team on how to best provide crash dump and/or ETW trace from the build?",
        "createdAt": "2023-07-13T16:38:05Z",
        "updatedAt": "2023-07-13T16:38:05Z",
        "author": {
          "login": "JanKrivanek"
        }
      },
      {
        "body": "@rmoreirao are you setting `msbuildArchitecture: 'x64'`?",
        "createdAt": "2023-07-13T16:42:41Z",
        "updatedAt": "2023-07-13T16:42:41Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "Hi, yes.. In the end we figured out the if we use maxCpuCount=3 (even though we have 8 cores), then the problem is solved. But if we increase that, we start receive all kind of different errors. It was not only GetEnvironmentVariables - so we decided to keep it like this.\r\n\r\nWhat do you think? Is this something it would still be worth exploring considering that we are receiving all different kind of errors? Or just let it like this?\r\n\r\nHere is the other example:\r\n\r\nUNHANDLED EXCEPTIONS FROM PROCESS 4512:\r\n=====================\r\n7/13/2023 1:54:06 PM\r\nSystem.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.\r\n   at Microsoft.NET.Build.Tasks.TaskBase.LogErrorTelemetry(String eventName, Exception e)\r\n   at Microsoft.NET.Build.Tasks.TaskBase.Execute()\r\n   at Microsoft.NET.Build.Tasks.TaskWithAssemblyResolveHooks.Execute()\r\n   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()",
        "createdAt": "2023-07-26T12:13:52Z",
        "updatedAt": "2023-07-26T12:13:52Z",
        "author": {
          "login": "rmoreirao"
        }
      },
      {
        "body": "Team triage: Does the issue ever happen on a developer machine? Unfortunately, without collecting more information (like dumps or ETW traces) we would not be able to figure out the reason of the failure.",
        "createdAt": "2023-08-02T15:23:03Z",
        "updatedAt": "2023-08-02T15:23:03Z",
        "author": {
          "login": "AR-May"
        }
      },
      {
        "body": "Hi, actually this is happening on Azure DevOps Agents - running on Windows 2019 Containers.\r\n",
        "createdAt": "2023-08-04T14:51:22Z",
        "updatedAt": "2023-08-04T14:51:22Z",
        "author": {
          "login": "rmoreirao"
        }
      },
      {
        "body": "@rmoreirao Do you have an infrastructure team you can consult on collecting dumps from ADO?\r\n\r\nI guess possibly setting some env vars to enable crash dump collection and setting the location (https://learn.microsoft.com/en-us/dotnet/core/diagnostics/collect-dumps-crash), and including the location to artifacts (regardless of success/error outcome of the run) might be a way forward here.\r\n\r\nBased on the manifestation via different stack it's not actionable for us - but dumpwould greatly help in uncovering the real source of bloating.",
        "createdAt": "2023-08-04T15:02:46Z",
        "updatedAt": "2023-08-04T15:02:46Z",
        "author": {
          "login": "JanKrivanek"
        }
      },
      {
        "body": "This issue is marked as stale because feedback has been requested for 30 days with no response. Please respond within 14 days or this issue will be closed due to inactivity.",
        "createdAt": "2023-09-10T00:01:08Z",
        "updatedAt": "2023-09-10T00:01:08Z",
        "author": {
          "login": "ghost"
        }
      },
      {
        "body": "This issue was closed due to inactivity. If you can still reproduce this bug, please comment with the requested information, detailed steps to reproduce the problem, or any other notes that might help in the investigation.",
        "createdAt": "2023-09-24T19:01:07Z",
        "updatedAt": "2023-09-24T19:01:07Z",
        "author": {
          "login": "ghost"
        }
      }
    ]
  }
}