{
  "number": 9129,
  "title": "[Unhandled Exception]: Items already exist for target AssignProjectConfiguration in a massively parallel build.",
  "body": "### Issue Description\r\n\r\nMassively parallel build (24 fully saturated cores (can do up to 64 effectively), no IncrediBuild, custom-made) keeps crashing on this error in about 50% of cases (2 out of 4 so far).\r\n\r\nWe are building 981 project configurations by one invocation using a customized build system that's I've authored through property sheets. It's been working fine for the past few years as long we don't immediately instantiate all 981 MSBuild tasks - the way we usually do it is to create new tasks once more dependencies are discovered and MSBuild has been completely stable doing that.\r\n\r\nHowever, I'm now experimenting with gathering all dependencies in advance and invoking all of them at once in order to increase the level of parallelization so the build won't ever run out of Targets to execute in parallel. The build script is still exactly the same, the only change is a large increase in the amount of concurrently executed targets. Since the error occurred for the first time while doing that, I would expect that there is a hidden synchronization problem somewhere in MSBuild that doesn't come to light unless there is massive overscheduling going on. \r\n\r\n\r\n   532>MSBUILD : error : This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled. [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :     Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Items already exist for target AssignProjectConfiguration. [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args) [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at Microsoft.Build.Execution.BuildResult.AddResultsForTarget(String target, TargetResult result) [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext() [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext() [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__68.MoveNext() [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\nMSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext() [d:\\Sources\\AvastClient\\features\\shredder\\src\\shredder\\shredder.vcxproj]\r\n\r\n\r\n### Steps to Reproduce\r\n\r\nI cannot unfortunately provide a full log or our projects as we're building the entire repo of Avast Antivirus and other products in this execution. If needed, I can share it privately with Microsoft if we have an NDA in place. I'm quite sure this issue in not reproducible without having a very large amount of projects connected with dependencies, I've not seen it without a massive parallelization in place. \r\n\r\nI can, however, gather info you request regarding the failing case and provide parts of the build script around this failure.\r\n\r\n### Actual Behavior\r\n\r\nUNHANDLED EXCEPTIONS FROM PROCESS 34576:\r\n=====================\r\n15. 8. 2023 14:45:33\r\nMicrosoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Items already exist for target AssignProjectConfiguration.\r\n   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)\r\n   at Microsoft.Build.Execution.BuildResult.AddResultsForTarget(String target, TargetResult result)\r\n   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__68.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()\r\n===================\r\n\r\n\r\n### Analysis\r\n\r\nLast time it happened 4 times during the same build invocation, each time with the same error. \r\n\r\n### Versions & Configurations\r\n\r\nMSBuild version 17.7.2+d6990bcfa for .NET Framework\r\n17.7.2.37605\r\nset MSBUILDCUSTOMSCHEDULER=WithConfigurationCountLevelling",
  "state": "CLOSED",
  "createdAt": "2023-08-15T13:04:49Z",
  "updatedAt": "2024-02-21T14:03:55Z",
  "closedAt": "2023-10-27T19:00:50Z",
  "author": {
    "login": "DeirhX"
  },
  "labels": [
    "bug",
    "needs-more-info",
    "stale",
    "closed-by-bot",
    "triaged"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "Note that happens also without MSBUILDCUSTOMSCHEDULER, reproduced again",
        "createdAt": "2023-08-15T14:42:00Z",
        "updatedAt": "2023-08-15T14:42:00Z",
        "author": {
          "login": "DeirhX"
        }
      },
      {
        "body": "@DeirhX thank you for reporting. A dump from repro (especially without the custom scheduler) would definitely be helpful - would it be possible to create ticket via https://developercommunity.visualstudio.com/dotnet/report, as you can upload artifacts (as e.g. the dump) privately and securely there? Feel free to shere the ticket here then",
        "createdAt": "2023-08-16T08:41:43Z",
        "updatedAt": "2023-08-16T08:41:43Z",
        "author": {
          "login": "JanKrivanek"
        }
      },
      {
        "body": "This issue is marked as stale because feedback has been requested for 30 days with no response. Please respond within 14 days or this issue will be closed due to inactivity.",
        "createdAt": "2023-10-13T00:00:44Z",
        "updatedAt": "2023-10-13T00:00:44Z",
        "author": {
          "login": "ghost"
        }
      },
      {
        "body": "This issue was closed due to inactivity. If you can still reproduce this bug, please comment with the requested information, detailed steps to reproduce the problem, or any other notes that might help in the investigation.",
        "createdAt": "2023-10-27T19:00:52Z",
        "updatedAt": "2023-10-27T19:00:52Z",
        "author": {
          "login": "ghost"
        }
      }
    ]
  }
}