{
  "number": 8440,
  "title": "Add exception message and stack strace for task DownloadFile fails",
  "body": "Fixes [#8407](https://github.com/dotnet/msbuild/issues/8407)\r\n\r\n### Context\r\nUnable to debug when exception message has fewer information.\r\n\r\n### Changes Made\r\nAdd exception stack trace\r\n\r\n### Testing\r\n![image](https://user-images.githubusercontent.com/26814373/218918889-d0237819-11c7-47c9-9305-ce7580716037.png)\r\n",
  "state": "MERGED",
  "createdAt": "2023-02-13T10:00:28Z",
  "updatedAt": "2023-03-03T21:03:42Z",
  "closedAt": "2023-02-21T01:41:40Z",
  "mergedAt": "2023-02-21T01:41:40Z",
  "additions": 1,
  "deletions": 1,
  "changedFiles": 1,
  "headRefName": "jennybai/issue8407",
  "isDraft": false,
  "author": {
    "login": "JaynieBai"
  },
  "milestone": null,
  "assignees": {
    "nodes": []
  },
  "labels": [
    "merge-when-branch-open"
  ],
  "commits": {
    "nodes": [
      {
        "commit": {
          "oid": "4b13b2c27aeae2e5f4a5eca4e806f4900c179ca1",
          "message": "Add stack strace for task DownloadFile",
          "committedDate": "2023-02-13T09:50:40Z",
          "author": {
            "name": "Jenny Bai",
            "email": "v-jennybai@microsoft.com"
          }
        }
      },
      {
        "commit": {
          "oid": "24f83d7c9616cc8bf9506c81e3c70dcd90ef6be3",
          "message": "revert actualException.Message to actualException",
          "committedDate": "2023-02-15T02:38:14Z",
          "author": {
            "name": "Jenny Bai",
            "email": "v-jennybai@microsoft.com"
          }
        }
      },
      {
        "commit": {
          "oid": "5b04fba9b6cb90fb9c5bd8ff6a3a5f6ce32f984f",
          "message": "revert resource changes",
          "committedDate": "2023-02-15T02:43:36Z",
          "author": {
            "name": "Jenny Bai",
            "email": "v-jennybai@microsoft.com"
          }
        }
      },
      {
        "commit": {
          "oid": "1401d763ccf90e5ea1ea4daafd6f0d05b84c726f",
          "message": "Revert \"Add stack strace for task DownloadFile\"\n\nThis reverts commit 4b13b2c27aeae2e5f4a5eca4e806f4900c179ca1.",
          "committedDate": "2023-02-15T03:19:44Z",
          "author": {
            "name": "Jenny Bai",
            "email": "v-jennybai@microsoft.com"
          }
        }
      }
    ]
  },
  "comments": {
    "nodes": [
      {
        "body": "We should only log stack trace when there is a bug in MSBuild or a task or logger. In other cases it is unlikely to be useful to anyone and looks like a bug in the product. I recently merged a change to remove such a stack. Is that what is proposed here?",
        "createdAt": "2023-02-16T05:28:40Z",
        "author": {
          "login": "danmoseley"
        }
      },
      {
        "body": "I see it is. What is the value to the user? How does it not look like the build crashed?",
        "createdAt": "2023-02-16T05:30:11Z",
        "author": {
          "login": "danmoseley"
        }
      },
      {
        "body": "https://github.com/dotnet/msbuild/pull/8271 did the opposite, because as a user I thought it was a bug (and it's certainly a mess, and wasn't necessary)\r\n\r\nAll the information is in the concatenated messages, not the stack.",
        "createdAt": "2023-02-16T05:44:07Z",
        "author": {
          "login": "danmoseley"
        }
      },
      {
        "body": "> I see it is. What is the value to the user? How does it not look like the build crashed?\r\n\r\nBased on the user's error info [error MSB3923: Failed to download file \"https://github.com/bytecodealliance/wasmtime/releases/download/dev/wasmtime-dev-aarch64-linux-c-api.tar.xz\". **Authentication failed, see inner exception**.](https://github.com/dotnet/msbuild/issues/8407#issuecomment-1420091457) ,which the inner Exception message is output before. But it's still not enough.\r\n",
        "createdAt": "2023-02-20T03:23:51Z",
        "author": {
          "login": "JaynieBai"
        }
      },
      {
        "body": "@JaynieBai the linked message says \"Authentication failed, see inner exception.\" What they need is the message from the inner exception. Using `ToString()` here is the wrong fix as it dumps the stack as well. \r\n\r\nYou just need to append the inner exception message if there is one. I believe the correct fix is something like this:\r\n\r\n```c#\r\nStringBuilder flattenedMessage= new StringBuilder(actualException.Message);\r\nException e = actualException;\r\nwhile (e.InnerException != null)\r\n{\r\n    e = e.InnerException;\r\n    flattenedMessage.Append(\" \").Append(e.Message);\r\n}\r\nLog.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl, flattenedMessage.ToString());\r\n```\r\n\r\nThe fix you have made here will look like an MSBuild bug in the log. Please reconsider and use code like the above.",
        "createdAt": "2023-02-21T02:45:21Z",
        "author": {
          "login": "danmoseley"
        }
      },
      {
        "body": "> You just need to append the inner exception message if there is one. I believe the correct fix is something like this:\r\n\r\nThanks for your good ideas. But I'm afraid of the concatenating strings are not coherent. I'm wondering if there is a diagnostic option that can control the output of error message.",
        "createdAt": "2023-02-24T07:43:16Z",
        "author": {
          "login": "JaynieBai"
        }
      },
      {
        "body": "Could you say more about why you believe they may not be coherent?\nWe already concatenate exception messages to MSBuild strings all over the codebase.\nHowever if it's still a concern, you can insert something between each, such as a newline.",
        "createdAt": "2023-03-02T03:18:54Z",
        "author": {
          "login": "danmoseley"
        }
      },
      {
        "body": "Another option is to use `--->` to separate, but on the same line. We already have plenty of precedent for this, eg., \r\n\r\nhttps://github.com/dotnet/runtime/blob/f70d8a9663d3d674c453e26d405dc13baa79fd16/src/libraries/System.Private.CoreLib/src/System/IO/FileLoadException.cs#L52-L56\r\n\r\nthis is used in FileNotFoundException, BadImageFormatException, and FileLoadException today. (Note, they don't have a loop, they only include the inner exception, but any inner exception can in theory and inner exception, so I'm proposing a loop to make certain nothing is missed.)\r\n\r\ncc @rainersigwald ",
        "createdAt": "2023-03-03T21:03:42Z",
        "author": {
          "login": "danmoseley"
        }
      }
    ]
  },
  "reviewThreads": {
    "nodes": [
      {
        "comments": {
          "nodes": [
            {
              "body": "This makes one error into two errors, right? Can you instead take the output the LogErrorFromException would log and replace actualException.Message with that? (And make sure it looks reasonable, since I haven't checked that.)",
              "createdAt": "2023-02-13T16:07:19Z",
              "path": "src/Tasks/DownloadFile.cs",
              "diffHunk": "@@ -125,7 +125,8 @@ private async Task<bool> ExecuteAsync()\n                     }\n                     else\n                     {\n-                        Log.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl, actualException.Message);\n+                        Log.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl);\n+                        Log.LogErrorFromException(actualException, true);",
              "author": {
                "login": "Forgind"
              }
            },
            {
              "body": "actualException.Message is original output.  Log.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl); is for the sourceUrl info. after that, add the detailed message and stack trace.  Just as image as above.  I use the 'Error message as follows' to make it united. \r\n![image](https://user-images.githubusercontent.com/26814373/218616601-9c004c56-c008-40f8-a027-39ff59d6a10c.png)\r\n",
              "createdAt": "2023-02-14T01:52:58Z",
              "path": "src/Tasks/DownloadFile.cs",
              "diffHunk": "@@ -125,7 +125,8 @@ private async Task<bool> ExecuteAsync()\n                     }\n                     else\n                     {\n-                        Log.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl, actualException.Message);\n+                        Log.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl);\n+                        Log.LogErrorFromException(actualException, true);",
              "author": {
                "login": "JaynieBai"
              }
            },
            {
              "body": "I agree that the error looks good; that isn't my concern. My concern is that if you look a little below your screenshot, I suspected it would say 2 errors instead of 1, and indeed it does:\r\n<img width=\"123\" alt=\"image\" src=\"https://user-images.githubusercontent.com/12969783/218898133-e81acd39-f0ed-439d-8dbe-b5a0a811c078.png\">\r\n\r\nMy suggestion isn't to change the content but to tell MSBuild it's only logging one error so that count is correct.",
              "createdAt": "2023-02-15T01:02:20Z",
              "path": "src/Tasks/DownloadFile.cs",
              "diffHunk": "@@ -125,7 +125,8 @@ private async Task<bool> ExecuteAsync()\n                     }\n                     else\n                     {\n-                        Log.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl, actualException.Message);\n+                        Log.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl);\n+                        Log.LogErrorFromException(actualException, true);",
              "author": {
                "login": "Forgind"
              }
            },
            {
              "body": "Sorry, I didn't notice that.   Now I change the actualException.Message to actualException.ToString().  The output is \r\n![image](https://user-images.githubusercontent.com/26814373/218919280-0d98051f-31d4-4c41-99a2-87625f109641.png)\r\n",
              "createdAt": "2023-02-15T03:24:15Z",
              "path": "src/Tasks/DownloadFile.cs",
              "diffHunk": "@@ -125,7 +125,8 @@ private async Task<bool> ExecuteAsync()\n                     }\n                     else\n                     {\n-                        Log.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl, actualException.Message);\n+                        Log.LogErrorWithCodeFromResources(\"DownloadFile.ErrorDownloading\", SourceUrl);\n+                        Log.LogErrorFromException(actualException, true);",
              "author": {
                "login": "JaynieBai"
              }
            }
          ]
        }
      }
    ]
  }
}